package com.app;
// Generated 28 Nov, 2016 12:34:41 PM by Hibernate Tools 3.6.0



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String email;
     private String pass;

    public Admin() {
    }

    public Admin(String email, String pass) {
       this.email = email;
       this.pass = pass;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


