package com.app;
// Generated 28 Nov, 2016 12:34:41 PM by Hibernate Tools 3.6.0



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private String name;
     private String email;
     private String subject;
     private String message;

    public Contact() {
    }

    public Contact(String name, String email, String subject, String message) {
       this.name = name;
       this.email = email;
       this.subject = subject;
       this.message = message;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


