package com.app;
// Generated 28 Nov, 2016 12:34:41 PM by Hibernate Tools 3.6.0



/**
 * Disease generated by hbm2java
 */
public class Disease  implements java.io.Serializable {


     private Integer id;
     private String dname;
     private String sym;

    public Disease() {
    }

	
    public Disease(String dname) {
        this.dname = dname;
    }
    public Disease(String dname, String sym) {
       this.dname = dname;
       this.sym = sym;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getSym() {
        return this.sym;
    }
    
    public void setSym(String sym) {
        this.sym = sym;
    }




}


