package com.app;
// Generated 28 Nov, 2016 12:34:41 PM by Hibernate Tools 3.6.0



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private String name;
     private String desc;

    public Feedback() {
    }

    public Feedback(String name, String desc) {
       this.name = name;
       this.desc = desc;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


