package com.app;
// Generated 28 Nov, 2016 12:34:41 PM by Hibernate Tools 3.6.0



/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private String email;
     private String name;
     private String pass;
     private String dob;
     private String country;
     private String gender;

    public Patient() {
    }

    public Patient(String email, String name, String pass, String dob, String country, String gender) {
       this.email = email;
       this.name = name;
       this.pass = pass;
       this.dob = dob;
       this.country = country;
       this.gender = gender;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


